### ISSUE TITLE
Issues with the results of SearchEngine

### ISSUE THREAD

**Issue by artificial-max** [eazteregg/Pun-Intended#15]
> Start search: "Sounds like x" "Has to do with y":
cat dog
['K', 'AE1', 'T']
[('cat', 1), ("cat's", 17), ('cas', 84), ('rat', 104), ('cats', 119)]

sounds_like: cat should not result in "cat"

> Start search: "Sounds like x" "Has to do with y":
> that argument
['DH', 'AE1', 'T']
[('that', 74), ('than', 902), ('arguments', 100000000), ('question', 100000001), ('ratte', 100000002)]

**Comment by artificial-max** [comment]
Fixed. If lemma of soundslike word equals best result, the second best result is chosen and so on.

**Comment by artificial-max** [comment]
**New problem:**
>Start search: "Sounds like x" "Has to do with y":
> test shit
['T', 'EH1', 'S', 'T']
best result: messed
[('messed', 202), ('fuck', 100000000), ('test', 100000000), ("test's", 100000001), ('crap', 100000001)]

After 'messed', the results seem to originate from the topic only. This is probably not ideal.

**Comment by eazteregg** [comment]
To me test and test's do not belong to the topic, but to the phonetics part of the affair. In any case, I have modified SearchEngine to disallow words in the phonetic list which have the same pronunciation as the sounds like word and now the other words it comes up with are arrest and attest
