### ISSUE TITLE
Different scores (for different .bins?)

### ISSUE THREAD

**Issue by artificial-max** [eazteregg/Pun-Intended#19]
my first .bin:
lose alcohol
[('booze', 39), ('laws', 371), ('lows', 381), ("law's", 606), ('dues', 632)]

my second .bin
[('booze', 42), ('lows', 338), ('laws', 368), ('dues', 586), ("law's", 627)]

first .bin AGAIN
[('booze', 54), ('laws', 321), ('lows', 349), ('dues', 523), ("law's", 613)]

Rerun without changing bin
[("law's", 57), ('booze', 127), ('lows', 384), ('dues', 559), ("do's", 768)]

Rerun 2
[('booze', 57), ("law's", 75), ('lows', 312), ('dues', 598), ("do's", 751)]

No bin:
[('booze', 30), ("law's", 73), ('lows', 386), ('dues', 624), ("do's", 780)]

No bin rerun 1:
[('booze', 77), ('lows', 332), ('laws', 365), ('dues', 527), ("law's", 618)]

No bin rerun 2:
[('booze', 55), ("law's", 78), ('lows', 302), ('dues', 629), ("do's", 825)]

**Comment by eazteregg** [comment]
For some weird reason I fail to replicate your results. Regardless of which file, be it .bin or .txt, I use, I always get the same results - same order, same score. I have put together some unittests to see if this is a problem on your machine only.

**Comment by lenakmeth** [comment]
Deleted everything (something was left in my .git) and pulled fresh.

Result after making bin for the first time:
lose alcohol
best result: booze
[('booze', 29), ('laws', 264), ('lows', 347), ('dues', 513), ("law's", 616)]

Shut down, restarted, using the same bin:
lose alcohol
best result: booze
[('booze', 29), ('laws', 264), ('lows', 347), ('dues', 513), ("law's", 616)]

Shut down, deleted binary file, made bin file again:
lose alcohol
best result: booze
[('booze', 29), ('laws', 264), ('lows', 347), ('dues', 513), ("law's", 616)]

I get consistently the same results. What do you mean by "no binary file"? Running the programme without a binary file?

**Comment by eazteregg** [comment]
When loading in the vector files, you may choose between .txt format and .bin format, while .bin loads a lot faster. The conversion from .txt to .bin is done by gensim. Normally, there shouldn't be any difference between the two, but the possibility existed that either gensim computes different bin files for different machines or even different bin files for different runs of the conversion which is what was happening on Max's laptop last friday.

**Comment by AnnaVechkaeva** [comment]
I also get different scores for .bin and .txt
first without .bin:
[("law's", 49), ('booze', 150), ('lows', 285), ('dues', 546), ("do's", 767)]

second without .bin
[("law's", 81), ('booze', 141), ('lows', 390), ('dues', 554), ("do's", 821)]

first with .bin:
[('booze', 87), ('laws', 330), ('lows', 336), ('dues', 585), ("law's", 615)]

second with .bin:
[('booze', 58), ('laws', 318), ('lows', 339), ('dues', 611), ("law's", 642)]

**Comment by AnnaVechkaeva** [comment]
I think I fixed it. Now it generates the same scores. At least on my computer. 
The problem was not with vectors generation but with sorting by edit distance score. The sort function probably works differently under different operation systems or on different computers. I think that if two words have the same distance, for example, on my computer, it would just put the words in random order, while on other computers it would put them in alphabetical order. That's why we were getting different scores on different runs.

**Comment by eazteregg** [comment]
nice i'm gonna close this then :D
