### ISSUE TITLE
use g2p in SearchEngine

### ISSUE THREAD

**Issue by artificial-max** [eazteregg/Pun-Intended#21]
Look at line 96 in SearchEngine.py

`        if not ortho and not rhyme:  # Default case: Use CMU dict
            iterlist = self.phondict  # The list being iterated over is thus the CMU dict

            try:
                phon_rep = iterlist[word][0]  # CMU dict returns a list of pronunciations, thus [0]

            except KeyError:

                try:
                    # TODO: Why do we not get here?
                    print("use g2p for: " + word)
                    phon_rep = self.g2p.decode_word(word)`

**Comment by eazteregg** [comment]
Remember that we only go in there if the word in question is not in the cmu dict. One example of that would be 'handbasket'. In which case, we do get there, the only problem was that you misnamed g2p. It should be g2p_model instead. Fixed this in the latest commit d8e59206074876dc9caecd10bf617d3cd4928ba2
