### ISSUE TITLE
prompt nltk.download() if cmudict is missing

### ISSUE THREAD

**Issue by artificial-max** [eazteregg/Pun-Intended#7]

**Comment by lenakmeth** [comment]
The change in SearchEngine.py (lines 6-11) raises an error for me (it says that cmudict doesn't exist, even though it definitely exists).

**Comment by eazteregg** [comment]
forgot to add the pronouncing package to the error message...you will have to download that as well

**Comment by artificial-max** [comment]
Hotfixed that last week in the combination branch.
Since I merged the branches, the hotfix now also works in master.
TODO: Better way to do it: Look at Jon's projects.
