### ISSUE TITLE
Add the first line in the vector file automatically (400000 100)

### ISSUE THREAD

**Issue by artificial-max** [eazteregg/Pun-Intended#9]
Currently, when the first line of glove.6B.100d.txt is not "400000 100", SearchEngine.py crashes.

**Comment by eazteregg** [comment]
at what point does it crash? the value error should be excepted in SearchEngine.py and then a word2vec formatted file should be created. at least, that's what it's doing on my end.

**Comment by eazteregg** [comment]
I know you showed it to me last week, but try as I might, I cannot reproduce the error on my end.

**Comment by artificial-max** [comment]
Fixed. With commit 7b84d090842dec7aca72cabd40d7f0ff33c416c5
